"""Independent models.dev catalogue and interchangeable model implementations."""

from .catalogue import MODELS_DEV_API_URL
from .auth import (
    ApiKeyCredential,
    ApiKeyResolution,
    AuthenticationError,
    AuthenticationStatus,
    ChatGPTLoginFlow,
    ChatGPTTokens,
    CredentialStore,
    CursorLoginFlow,
    CursorTokens,
    DeviceLoginFlow,
    EnvironmentCredential,
    LoginFlow,
    InMemoryCredentialStore,
    OAuthAdapter,
    OAuthAuthorization,
    OAuthConfiguration,
    OAuthLoginFlow,
    OAuthProvider,
    OAuthTokens,
    ProviderAuthentication,
    ProviderAuthProfile,
    bind_credential_store,
    current_credential_store,
    reset_credential_store,
    request_chatgpt_headers,
    request_cursor_headers,
    chatgpt_tokens,
    cursor_tokens,
    valid_chatgpt_tokens,
    valid_cursor_tokens,
    provider_auth_profile,
)
from .subscriptions import (
    cached_chatgpt_models,
    cached_cursor_models,
    capture_usage_headers,
    clear_chatgpt_models_cache,
    clear_cursor_models_cache,
    clear_usage_snapshot,
    display_cursor_account,
    fetch_chatgpt_models,
    fetch_cursor_models,
    get_usage_snapshot,
    set_usage_snapshot,
)
from .core import ModelProvider, ModelUsage, ModelRecord, ProviderRecord
from .usage import UsageLedger, UsageSnapshot, UsageWindow
from .facade import Models

__all__ = [
    "MODELS_DEV_API_URL",
    "ApiKeyCredential",
    "ApiKeyResolution",
    "AuthenticationError",
    "AuthenticationStatus",
    "ChatGPTLoginFlow",
    "ChatGPTTokens",
    "CredentialStore",
    "CursorLoginFlow",
    "CursorTokens",
    "DeviceLoginFlow",
    "EnvironmentCredential",
    "LoginFlow",
    "InMemoryCredentialStore",
    "OAuthAdapter",
    "OAuthAuthorization",
    "OAuthConfiguration",
    "OAuthLoginFlow",
    "OAuthProvider",
    "OAuthTokens",
    "ModelUsage",
    "ModelProvider",
    "ModelRecord",
    "ProviderRecord",
    "ProviderAuthentication",
    "ProviderAuthProfile",
    "provider_auth_profile",
    "UsageLedger",
    "UsageSnapshot",
    "UsageWindow",
    "bind_credential_store",
    "current_credential_store",
    "Models",
    "reset_credential_store",
    "request_chatgpt_headers",
    "request_cursor_headers",
    "chatgpt_tokens",
    "cursor_tokens",
    "valid_chatgpt_tokens",
    "valid_cursor_tokens",
    "cached_chatgpt_models",
    "cached_cursor_models",
    "capture_usage_headers",
    "clear_chatgpt_models_cache",
    "clear_cursor_models_cache",
    "clear_usage_snapshot",
    "display_cursor_account",
    "fetch_chatgpt_models",
    "fetch_cursor_models",
    "get_usage_snapshot",
    "set_usage_snapshot",
    "LiteLLMChatModel",
    "LiteLLMProvider",
    "provider_registry",
]


def __getattr__(name: str):
    """Load the optional heavy transport implementation only when requested."""
    if name in {"LiteLLMChatModel", "LiteLLMProvider", "provider_registry"}:
        from .litellm import LiteLLMChatModel, LiteLLMProvider, provider_registry

        return {
            "LiteLLMChatModel": LiteLLMChatModel,
            "LiteLLMProvider": LiteLLMProvider,
            "provider_registry": provider_registry,
        }[name]
    raise AttributeError(name)
