"""Provider-neutral usage and account-limit records."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field, replace
from datetime import datetime, timezone
from threading import Lock
from pydantic import (
    AliasChoices,
    BaseModel,
    ConfigDict,
    Field,
    ValidationError,
    ValidationInfo,
    field_validator,
)

__all__ = [
    "AudioUsage",
    "CacheUsage",
    "CostUsage",
    "ModelUsage",
    "TokenUsage",
    "UsageLedger",
    "UsageSnapshot",
    "UsageWindow",
]


class _UsagePayloadBase(BaseModel):
    model_config = ConfigDict(extra="ignore")

    @field_validator("*", mode="before")
    @classmethod
    def normalize_numbers(cls, value: object, info: ValidationInfo) -> object:
        if value is None:
            return None
        if not isinstance(value, (int, float, str)):
            return None
        try:
            if info.field_name in {
                "input_tokens",
                "output_tokens",
                "total_tokens",
                "reasoning_tokens",
                "cache_read_tokens",
                "cache_write_tokens",
                "input_audio_tokens",
                "output_audio_tokens",
            }:
                return int(value)
            if info.field_name == "cost_usd":
                return float(value)
        except (ValueError, OverflowError):
            return None
        return value


class _TokenPayload(_UsagePayloadBase):
    input_tokens: int | None = Field(
        default=None, validation_alias=AliasChoices("input_tokens", "prompt_tokens")
    )
    output_tokens: int | None = Field(
        default=None, validation_alias=AliasChoices("output_tokens", "completion_tokens")
    )
    total_tokens: int | None = None
    reasoning_tokens: int | None = None


class _CachePayload(_UsagePayloadBase):
    cache_read_tokens: int | None = Field(
        default=None,
        validation_alias=AliasChoices("cache_read_tokens", "cached_tokens", "cache_read"),
    )
    cache_write_tokens: int | None = Field(
        default=None,
        validation_alias=AliasChoices("cache_write_tokens", "cache_creation", "cache_write"),
    )


class _AudioPayload(_UsagePayloadBase):
    input_audio_tokens: int | None = None
    output_audio_tokens: int | None = None


class _CostPayload(_UsagePayloadBase):
    cost_usd: float | None = Field(default=None, validation_alias=AliasChoices("cost_usd", "usd"))


class _UsagePayload(_UsagePayloadBase):
    tokens: _TokenPayload | None = None
    cache: _CachePayload | None = None
    audio: _AudioPayload | None = None
    cost: _CostPayload | float | None = None
    input_tokens: int | None = Field(
        default=None, validation_alias=AliasChoices("input_tokens", "prompt_tokens")
    )
    output_tokens: int | None = Field(
        default=None, validation_alias=AliasChoices("output_tokens", "completion_tokens")
    )
    total_tokens: int | None = None
    reasoning_tokens: int | None = None
    cache_read_tokens: int | None = Field(
        default=None, validation_alias=AliasChoices("cache_read_tokens", "cached_tokens")
    )
    cache_write_tokens: int | None = None
    input_audio_tokens: int | None = None
    output_audio_tokens: int | None = None
    cost_usd: float | None = None
    output_token_details: _TokenPayload | None = None
    completion_tokens_details: _TokenPayload | None = None
    input_token_details: _CachePayload | None = None
    prompt_tokens_details: _CachePayload | None = None
    reasoning_tokens_details: _TokenPayload | None = None


@dataclass(frozen=True, slots=True)
class TokenUsage:
    """Token counts normalized from a provider response."""

    input_tokens: int = field(default=0, metadata={"description": "Tokens sent to the model."})
    output_tokens: int = field(
        default=0, metadata={"description": "Tokens generated by the model."}
    )
    total_tokens: int = field(default=0, metadata={"description": "Input plus output tokens."})
    reasoning_tokens: int = field(
        default=0, metadata={"description": "Output tokens spent on reasoning."}
    )


@dataclass(frozen=True, slots=True)
class CacheUsage:
    """Prompt-cache token counts normalized from a provider response."""

    cache_read_tokens: int = field(
        default=0, metadata={"description": "Tokens read from the prompt cache."}
    )
    cache_write_tokens: int = field(
        default=0, metadata={"description": "Tokens written to the prompt cache."}
    )


@dataclass(frozen=True, slots=True)
class AudioUsage:
    """Audio token counts normalized from a provider response."""

    input_audio_tokens: int = field(
        default=0, metadata={"description": "Audio tokens sent to the model."}
    )
    output_audio_tokens: int = field(
        default=0, metadata={"description": "Audio tokens generated by the model."}
    )


@dataclass(frozen=True, slots=True)
class CostUsage:
    """Monetary cost normalized from a provider response."""

    cost_usd: float = field(
        default=0.0, metadata={"description": "Estimated provider cost in US dollars."}
    )


@dataclass(frozen=True, slots=True)
class ModelUsage:
    """Normalized usage grouped by measurement type for one model response."""

    tokens: TokenUsage = field(default_factory=TokenUsage)
    cache: CacheUsage = field(default_factory=CacheUsage)
    audio: AudioUsage = field(default_factory=AudioUsage)
    cost: CostUsage = field(default_factory=CostUsage)

    @classmethod
    def from_mapping(cls, value: Mapping[str, object] | None) -> "ModelUsage":
        try:
            payload = _UsagePayload.model_validate(value or {})
        except ValidationError:
            payload = _UsagePayload()
        tokens = payload.tokens or _TokenPayload(
            input_tokens=payload.input_tokens,
            output_tokens=payload.output_tokens,
            total_tokens=payload.total_tokens,
            reasoning_tokens=payload.reasoning_tokens,
        )
        input_tokens = max(0, tokens.input_tokens or 0)
        output_tokens = max(0, tokens.output_tokens or 0)
        total_tokens = max(0, tokens.total_tokens or input_tokens + output_tokens)
        output_details = payload.output_token_details or payload.completion_tokens_details
        input_details = payload.input_token_details or payload.prompt_tokens_details
        reasoning_details = payload.reasoning_tokens_details
        reasoning_value = (
            tokens.reasoning_tokens
            or (output_details.reasoning_tokens if output_details else 0)
            or (reasoning_details.reasoning_tokens if reasoning_details else 0)
            or 0
        )
        reasoning_tokens = max(0, reasoning_value)
        cache = payload.cache or _CachePayload(
            cache_read_tokens=payload.cache_read_tokens,
            cache_write_tokens=payload.cache_write_tokens,
        )
        cache_read_value = (
            cache.cache_read_tokens
            or (input_details.cache_read_tokens if input_details else 0)
            or 0
        )
        cache_write_value = (
            cache.cache_write_tokens
            or (input_details.cache_write_tokens if input_details else 0)
            or 0
        )
        cache_read_tokens = max(0, cache_read_value)
        cache_write_tokens = max(0, cache_write_value)
        audio = payload.audio or _AudioPayload(
            input_audio_tokens=payload.input_audio_tokens,
            output_audio_tokens=payload.output_audio_tokens,
        )
        cost = payload.cost
        cost_usd = cost.cost_usd if isinstance(cost, _CostPayload) else cost
        if cost_usd is None:
            cost_usd = payload.cost_usd
        return cls(
            tokens=TokenUsage(
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                total_tokens=total_tokens,
                reasoning_tokens=reasoning_tokens,
            ),
            cache=CacheUsage(
                cache_read_tokens=cache_read_tokens,
                cache_write_tokens=cache_write_tokens,
            ),
            audio=AudioUsage(
                input_audio_tokens=max(0, audio.input_audio_tokens or 0),
                output_audio_tokens=max(0, audio.output_audio_tokens or 0),
            ),
            cost=CostUsage(cost_usd=max(0.0, cost_usd or 0.0)),
        )


@dataclass(frozen=True, slots=True)
class UsageWindow:
    """One provider-reported rate-limit window."""

    name: str
    used_percent: float = 0.0
    duration_minutes: int = 0
    resets_at: int | None = None


@dataclass(frozen=True, slots=True)
class UsageSnapshot:
    """A provider account's latest quota snapshot, safe to serialize and publish."""

    provider: str
    captured_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    plan: str = ""
    active_limit: str = ""
    credit_balance: float | None = None
    has_credits: bool = False
    unlimited_credits: bool = False
    windows: tuple[UsageWindow, ...] = ()


class UsageLedger:
    """Thread-safe in-memory totals keyed by provider-qualified model identifier."""

    def __init__(self) -> None:
        self._totals: dict[str, ModelUsage] = {}
        self._lock = Lock()

    def record(self, model_identifier: str, usage: ModelUsage) -> ModelUsage:
        with self._lock:
            current = self._totals.get(model_identifier, ModelUsage())
            total = replace(
                current,
                tokens=replace(
                    current.tokens,
                    input_tokens=current.tokens.input_tokens + usage.tokens.input_tokens,
                    output_tokens=current.tokens.output_tokens + usage.tokens.output_tokens,
                    total_tokens=current.tokens.total_tokens + usage.tokens.total_tokens,
                    reasoning_tokens=current.tokens.reasoning_tokens
                    + usage.tokens.reasoning_tokens,
                ),
                cache=replace(
                    current.cache,
                    cache_read_tokens=current.cache.cache_read_tokens
                    + usage.cache.cache_read_tokens,
                    cache_write_tokens=current.cache.cache_write_tokens
                    + usage.cache.cache_write_tokens,
                ),
                audio=replace(
                    current.audio,
                    input_audio_tokens=current.audio.input_audio_tokens
                    + usage.audio.input_audio_tokens,
                    output_audio_tokens=current.audio.output_audio_tokens
                    + usage.audio.output_audio_tokens,
                ),
                cost=replace(current.cost, cost_usd=current.cost.cost_usd + usage.cost.cost_usd),
            )
            self._totals[model_identifier] = total
            return total

    def get(self, model_identifier: str) -> ModelUsage:
        with self._lock:
            return self._totals.get(model_identifier, ModelUsage())

    def snapshot(self) -> dict[str, ModelUsage]:
        with self._lock:
            return dict(self._totals)
