"""Provider-neutral usage and account-limit records."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field, replace
from datetime import datetime, timezone
from threading import Lock
from typing import Any

__all__ = [
    "AudioUsage",
    "CacheUsage",
    "CostUsage",
    "ModelUsage",
    "TokenUsage",
    "UsageLedger",
    "UsageSnapshot",
    "UsageWindow",
]


def _integer(value: Any) -> int:
    try:
        return max(0, int(value or 0))
    except (TypeError, ValueError):
        return 0


def _mapping(value: Any) -> Mapping[str, Any]:
    return value if isinstance(value, Mapping) else {}


@dataclass(frozen=True, slots=True)
class TokenUsage:
    """Token counts normalized from a provider response."""

    input_tokens: int = field(default=0, metadata={"description": "Tokens sent to the model."})
    output_tokens: int = field(
        default=0, metadata={"description": "Tokens generated by the model."}
    )
    total_tokens: int = field(default=0, metadata={"description": "Input plus output tokens."})
    reasoning_tokens: int = field(
        default=0, metadata={"description": "Output tokens spent on reasoning."}
    )


@dataclass(frozen=True, slots=True)
class CacheUsage:
    """Prompt-cache token counts normalized from a provider response."""

    cache_read_tokens: int = field(
        default=0, metadata={"description": "Tokens read from the prompt cache."}
    )
    cache_write_tokens: int = field(
        default=0, metadata={"description": "Tokens written to the prompt cache."}
    )


@dataclass(frozen=True, slots=True)
class AudioUsage:
    """Audio token counts normalized from a provider response."""

    input_audio_tokens: int = field(
        default=0, metadata={"description": "Audio tokens sent to the model."}
    )
    output_audio_tokens: int = field(
        default=0, metadata={"description": "Audio tokens generated by the model."}
    )


@dataclass(frozen=True, slots=True)
class CostUsage:
    """Monetary cost normalized from a provider response."""

    cost_usd: float = field(
        default=0.0, metadata={"description": "Estimated provider cost in US dollars."}
    )


@dataclass(frozen=True, slots=True)
class ModelUsage:
    """Normalized usage grouped by measurement type for one model response."""

    tokens: TokenUsage = field(default_factory=TokenUsage)
    cache: CacheUsage = field(default_factory=CacheUsage)
    audio: AudioUsage = field(default_factory=AudioUsage)
    cost: CostUsage = field(default_factory=CostUsage)

    @classmethod
    def from_mapping(cls, value: Mapping[str, Any] | None) -> "ModelUsage":
        value = _mapping(value)
        token_values = _mapping(value.get("tokens"))
        cache_values = _mapping(value.get("cache"))
        audio_values = _mapping(value.get("audio"))
        cost_values = _mapping(value.get("cost"))
        input_tokens = _integer(
            token_values.get("input_tokens", value.get("input_tokens", value.get("prompt_tokens")))
        )
        output_tokens = _integer(
            token_values.get(
                "output_tokens", value.get("output_tokens", value.get("completion_tokens"))
            )
        )
        total_tokens = _integer(value.get("total_tokens")) or input_tokens + output_tokens
        if token_values.get("total_tokens"):
            total_tokens = _integer(token_values["total_tokens"])
        output_details = _mapping(
            value.get("output_token_details") or value.get("completion_tokens_details")
        )
        input_details = _mapping(
            value.get("input_token_details") or value.get("prompt_tokens_details")
        )
        reasoning_details = _mapping(value.get("reasoning_tokens_details"))
        raw_cost = value.get("cost_usd")
        if raw_cost is None:
            raw_cost = cost_values.get("cost_usd", cost_values.get("usd", value.get("cost")))
        try:
            cost_usd = max(
                0.0,
                float(raw_cost or 0.0),
            )
        except (TypeError, ValueError):
            cost_usd = 0.0
        return cls(
            tokens=TokenUsage(
                input_tokens=input_tokens,
                output_tokens=output_tokens,
                total_tokens=total_tokens,
                reasoning_tokens=_integer(
                    token_values.get("reasoning_tokens")
                    or value.get("reasoning_tokens")
                    or output_details.get("reasoning_tokens")
                    or reasoning_details.get("reasoning_tokens")
                    or reasoning_details.get("reasoning")
                ),
            ),
            cache=CacheUsage(
                cache_read_tokens=_integer(
                    cache_values.get("cache_read_tokens")
                    or value.get("cache_read_tokens")
                    or value.get("cached_tokens")
                    or input_details.get("cache_read")
                    or input_details.get("cached_tokens")
                ),
                cache_write_tokens=_integer(
                    cache_values.get("cache_write_tokens")
                    or value.get("cache_write_tokens")
                    or input_details.get("cache_creation")
                    or input_details.get("cache_write_tokens")
                ),
            ),
            audio=AudioUsage(
                input_audio_tokens=_integer(
                    audio_values.get("input_audio_tokens", value.get("input_audio_tokens"))
                ),
                output_audio_tokens=_integer(
                    audio_values.get("output_audio_tokens", value.get("output_audio_tokens"))
                ),
            ),
            cost=CostUsage(cost_usd=cost_usd),
        )


@dataclass(frozen=True, slots=True)
class UsageWindow:
    """One provider-reported rate-limit window."""

    name: str
    used_percent: float = 0.0
    duration_minutes: int = 0
    resets_at: int | None = None


@dataclass(frozen=True, slots=True)
class UsageSnapshot:
    """A provider account's latest quota snapshot, safe to serialize and publish."""

    provider: str
    captured_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    plan: str = ""
    active_limit: str = ""
    credit_balance: float | None = None
    has_credits: bool = False
    unlimited_credits: bool = False
    windows: tuple[UsageWindow, ...] = ()


class UsageLedger:
    """Thread-safe in-memory totals keyed by provider-qualified model identifier."""

    def __init__(self) -> None:
        self._totals: dict[str, ModelUsage] = {}
        self._lock = Lock()

    def record(self, model_identifier: str, usage: ModelUsage) -> ModelUsage:
        with self._lock:
            current = self._totals.get(model_identifier, ModelUsage())
            total = replace(
                current,
                tokens=replace(
                    current.tokens,
                    input_tokens=current.tokens.input_tokens + usage.tokens.input_tokens,
                    output_tokens=current.tokens.output_tokens + usage.tokens.output_tokens,
                    total_tokens=current.tokens.total_tokens + usage.tokens.total_tokens,
                    reasoning_tokens=current.tokens.reasoning_tokens
                    + usage.tokens.reasoning_tokens,
                ),
                cache=replace(
                    current.cache,
                    cache_read_tokens=current.cache.cache_read_tokens
                    + usage.cache.cache_read_tokens,
                    cache_write_tokens=current.cache.cache_write_tokens
                    + usage.cache.cache_write_tokens,
                ),
                audio=replace(
                    current.audio,
                    input_audio_tokens=current.audio.input_audio_tokens
                    + usage.audio.input_audio_tokens,
                    output_audio_tokens=current.audio.output_audio_tokens
                    + usage.audio.output_audio_tokens,
                ),
                cost=replace(current.cost, cost_usd=current.cost.cost_usd + usage.cost.cost_usd),
            )
            self._totals[model_identifier] = total
            return total

    def get(self, model_identifier: str) -> ModelUsage:
        with self._lock:
            return self._totals.get(model_identifier, ModelUsage())

    def snapshot(self) -> dict[str, ModelUsage]:
        with self._lock:
            return dict(self._totals)
